language: python

dist: xenial
sudo: required

services:
  - docker

matrix:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=py27
    - python: "3.6"
      env:
        - TOX_ENV=py36
    - python: "3.7"
      env:
        - TOX_ENV=py37
    - python: "3.8"
      env:
        - TOX_ENV=py38
    - python: "3.9"
      env:
        - TOX_ENV=py39
    - env:
        - DOCKER_COMPOSE_VERSION=1.27.4
      install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +rx docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - docker build . -t internap/fake-switches:latest
        - docker-compose up -d
        - docker inspect -f {{.State.Running}} fake-switches_tsr1.yul1.example.net_1
        - docker inspect -f {{.State.Running}} fake-switches_tor1.yul1.example.net_1

addons:
  apt:
    packages:
    - telnet

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - ssh-keygen -t rsa -b 1024 -f ~/.ssh/id_rsa -C fake@ssh -N ''

script:
  - tox -e $TOX_ENV
